### ISSUE TITLE
Feature Extension

### ISSUE THREAD

**Issue by hentai-chan** [hentai-chan/discord-hentai-bot#1]
# Feature Extension
## Request
This isssue addresses three new features, namely:

```python
    @staticmethod
    def get_homepage(page: int = 1) -> List[Hentai]:
        raise NotImplementedError()

    @staticmethod
    def convert2tag_name(tag_id: int) -> str:
        raise NotImplementedError()

    @staticmethod
    def search_by_tag(tag_name: str) -> List[Hentai]:
        raise NotImplementedError()
```

The first function is a no-brainer, but `search_by_tag` will depend on the conversion function `convert2tag_name`. It's much better for end-users to search tags by their string representation rather than their `tag_id`, though I have no idea yet which endpoint to use for the latter problem.

## Status
- [ ] `get_homepage`
- [ ] `convert2tag_name`
- [ ] `search_by_tag`

**Comment by Educorreia932** [comment]
Another useful feature would be to search by name, instead of just "magical numbers"

**Comment by hentai-chan** [comment]
closed as target of migration to a new repository.
